# Generated by Django 3.1.2 on 2020-10-28 23:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 23, 22, 39, 681807, tzinfo=utc), verbose_name='date published'),
        ),
    ]
